version: '3.1'

services:
  postgres:
    image: postgres
    networks:
      - postgres
    restart: always
    environment:
      POSTGRES_DB: fullstack-afiliados
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: Passw@rd
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql

  api:
    image: fullstack-afiliados-api
    build: ./backend
    env_file:
      - ./backend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

  front:
    image: fullstack-afiliados-front
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - postgres
    

volumes:
  db-volume: {}

networks:
  postgres:
    driver: bridge